test:
  'http://localhost:3000':
    acs_url: 'http://localhost:3000/test/saml/decode_assertion'
    assertion_consumer_logout_service_url: 'http://localhost:3000/test/saml/decode_slo_request'
    sp_initiated_login_url: 'http://localhost:3000/test/saml'
    block_encryption: 'none'
    cert: 'saml_test_sp'
    agency: 'Test Government Agency'
    friendly_name: 'Your friendly Government Agency'
    logo: 'generic.svg'
    return_to_sp_url: 'http://localhost:3000'
    attribute_bundle:
      - email
      - phone

  'https://rp1.serviceprovider.com/auth/saml/metadata':
    acs_url: 'http://example.com/test/saml/decode_assertion'
    assertion_consumer_logout_service_url: 'http://example.com/test/saml/decode_slo_request'
    block_encryption: 'aes256-cbc'
    sp_initiated_login_url: 'https://example.com/auth/saml/login'
    friendly_name: 'Test SP'
    cert: 'saml_test_sp'
    logo: 'generic.svg'
    attribute_bundle:
      - first_name
      - last_name
      - ssn
      - zipcode

  'https://rp2.serviceprovider.com/auth/saml/metadata':
    acs_url: 'http://example.com/test/saml/decode_assertion'
    assertion_consumer_logout_service_url: 'http://example.com/test/saml/decode_slo_request'
    block_encryption: 'aes256-cbc'
    cert: 'saml_test_sp'

  'http://test.host':
    acs_url: 'http://test.host/test/saml/decode_assertion'
    block_encryption: 'aes256-cbc'
    metadata_url: 'http://test.host/test/saml/metadata'
    sp_initiated_login_url: 'http://test.host/test/saml'

  'urn:gov:gsa:openidconnect:test':
    redirect_uris:
      - 'gov.gsa.openidconnect.test://result'
    cert: 'saml_test_sp'
    friendly_name: 'Example iOS App'
    agency: '18F'
    logo: 'generic.svg'

  'urn:gov:gsa:openidconnect:sp:server':
    redirect_uris:
      - 'http://localhost:7654/'
    cert: 'saml_test_sp'
    friendly_name: 'Test SP'
    assertion_consumer_logout_service_url: ''

development:
  'https://rp1.serviceprovider.com/auth/saml/metadata':
    metadata_url: 'http://localhost:3000/test/saml/metadata'
    acs_url: 'http://localhost:3000/test/saml/decode_assertion'
    assertion_consumer_logout_service_url: 'http://localhost:3000/test/saml/decode_slo_request'
    block_encryption: 'aes256-cbc'
    sp_initiated_login_url: 'http://localhost:3000/test/saml'
    cert: 'saml_test_sp'
    fingerprint: '08:79:F5:B1:B8:CC:EC:8F:5C:2A:58:03:30:14:C9:E6:F1:67:78:F1:97:E8:3A:88:EB:8E:70:92:25:D2:2F:32'
    logo: 'generic.svg'
    agency: 'GSA'
    friendly_name: 'Awesome test SP'

  'urn:gov:gsa:SAML:2.0.profiles:sp:sso:localhost':
    acs_url: 'http://localhost:4567/consume'
    sp_initiated_login_url: 'http://localhost:4567/test/saml'
    assertion_consumer_logout_service_url: 'http://localhost:4567/slo_logout'
    block_encryption: 'aes256-cbc'
    cert: 'sp_sinatra_demo'
    attribute_bundle:
      - email

  'urn:gov:gsa:SAML:2.0.profiles:sp:sso:localhost-micropurchase':
    acs_url: 'http://localhost:3000/auth/saml/callback'
    assertion_consumer_logout_service_url: 'http://localhost:3000/auth/saml/logout'
    sp_initiated_login_url: 'http://localhost:3000/admin/sign_in'
    block_encryption: 'aes256-cbc'
    cert: 'sp_micropurchase'
    agency: 'TTS Acquisition'
    logo: '18f.svg'
    friendly_name: 'Micro-purchase Dev'
    return_to_sp_url: 'http://localhost:3000'
    attribute_bundle:
      - email

  'urn:gov:gsa:SAML:2.0.profiles:sp:sso:localhost-rails':
    acs_url: 'http://localhost:3003/auth/saml/callback'
    assertion_consumer_logout_service_url: 'http://localhost:3003/auth/saml/logout'
    sp_initiated_login_url: 'http://localhost:3003/login'
    block_encryption: 'aes256-cbc'
    cert: 'sp_rails_demo'
    agency: '18F'
    friendly_name: '18F Test Service Provider'
    logo: 'generic.svg'
    return_to_sp_url: 'http://localhost:3003'
    attribute_bundle:
      - email

  'https://dashboard.login.gov':
    friendly_name: 'Dashboard'
    agency: 'GSA'
    logo: '18f.svg'
    acs_url: 'http://localhost:3001/users/auth/saml/callback'
    assertion_consumer_logout_service_url: 'http://localhost:3001/users/auth/saml/logout'
    sp_initiated_login_url: 'http://localhost:3001/users/auth/saml'
    block_encryption: 'aes256-cbc'
    cert: 'identity_dashboard_cert'
    attribute_bundle:
      - email

  'urn:gov:gsa:openidconnect:development':
    redirect_uris:
      - 'gov.gsa.openidconnect.development://result'
    friendly_name: 'Example iOS App'
    agency: '18F'
    logo: 'generic.svg'

  'urn:gov:gsa:openidconnect:sp:sinatra':
    redirect_uris:
      - 'http://localhost:9292/'
    cert: 'sp_sinatra_demo'
    friendly_name: 'Example Sinatra App'

production:
  'https://idp.dev.login.gov':
    metadata_url: 'https://idp.dev.login.gov/api/saml/metadata'
    acs_url: 'https://idp.dev.login.gov/test/saml/decode_assertion'
    assertion_consumer_logout_service_url: 'https://idp.dev.login.gov/test/saml/decode_logoutresponse'
    sp_initiated_login_url: 'https://idp.dev.login.gov/test/saml'
    block_encryption: 'aes256-cbc'
    cert: 'saml_test_sp'
    logo: 'generic.svg'
    agency: 'GSA'
    friendly_name: 'Awesome test SP'
    attribute_bundle:
      - email

  'urn:gov:gsa:SAML:2.0.profiles:sp:sso:localhost':
    acs_url: 'http://localhost:4567/consume'
    sp_initiated_login_url: 'http://localhost:4567/test/saml'
    block_encryption: 'aes256-cbc'
    cert: 'sp_sinatra_demo'
    attribute_bundle:
      - email

  'urn:gov:gsa:SAML:2.0.profiles:sp:sso:dev':
    acs_url: 'https://sp-sinatra.dev.login.gov/consume'
    assertion_consumer_logout_service_url: 'https://sp-sinatra.dev.login.gov/slo_logout'
    sp_initiated_login_url: 'https://sp-sinatra.dev.login.gov/test/saml'
    block_encryption: 'aes256-cbc'
    cert: 'sp_sinatra_demo'
    attribute_bundle:
      - email

  'urn:gov:gsa:SAML:2.0.profiles:sp:sso:demo':
    acs_url: 'https://sp-sinatra.demo.login.gov/consume'
    assertion_consumer_logout_service_url: 'https://sp-sinatra.demo.login.gov/slo_logout'
    sp_initiated_login_url: 'https://sp-sinatra.demo.login.gov/test/saml'
    block_encryption: 'aes256-cbc'
    cert: 'sp_sinatra_demo'
    attribute_bundle:
      - email

  'urn:gov:gsa:SAML:2.0.profiles:sp:sso:rails-dev':
    acs_url: 'https://sp.dev.login.gov/auth/saml/callback'
    assertion_consumer_logout_service_url: 'https://sp.dev.login.gov/auth/saml/logout'
    sp_initiated_login_url: 'https://sp.dev.login.gov/login'
    block_encryption: 'aes256-cbc'
    cert: 'sp_rails_demo'
    agency: 'A Gov Agency'
    friendly_name: 'Demo SP Application'
    logo: 'generic.svg'
    return_to_sp_url: 'https://sp.dev.login.gov'
    attribute_bundle:
      - email

  'urn:gov:gsa:SAML:2.0.profiles:sp:sso:rails-qa':
    acs_url: 'https://sp.qa.login.gov/auth/saml/callback'
    assertion_consumer_logout_service_url: 'https://sp.qa.login.gov/auth/saml/logout'
    sp_initiated_login_url: 'https://sp.qa.login.gov/login'
    block_encryption: 'aes256-cbc'
    cert: 'sp_rails_demo'
    agency: 'A Gov Agency'
    friendly_name: 'Demo SP Application'
    logo: 'generic.svg'
    return_to_sp_url: 'https://sp.qa.login.gov'
    attribute_bundle:
      - email

  'urn:gov:gsa:SAML:2.0.profiles:sp:sso:rails-int':
    acs_url: 'https://sp.int.login.gov/auth/saml/callback'
    assertion_consumer_logout_service_url: 'https://sp.int.login.gov/auth/saml/logout'
    sp_initiated_login_url: 'https://sp.int.login.gov/login'
    block_encryption: 'aes256-cbc'
    cert: 'sp_rails_demo'
    agency: 'A Gov Agency'
    friendly_name: 'Demo SP Application'
    logo: 'generic.svg'
    return_to_sp_url: 'https://sp.int.login.gov'
    attribute_bundle:
      - email

  'urn:gov:gsa:SAML:2.0.profiles:sp:sso:rails-demo':
    acs_url: 'https://sp.demo.login.gov/auth/saml/callback'
    assertion_consumer_logout_service_url: 'https://sp.demo.login.gov/auth/saml/logout'
    sp_initiated_login_url: 'https://sp.demo.login.gov/login'
    block_encryption: 'aes256-cbc'
    cert: 'sp_rails_demo'
    agency: 'A Gov Agency'
    friendly_name: 'Demo SP Application'
    logo: 'generic.svg'
    return_to_sp_url: 'https://sp.demo.login.gov'
    attribute_bundle:
      - email

# Micro-purchase
  'urn:gov:gsa:SAML:2.0.profiles:sp:sso:localhost-micropurchase':
    acs_url: 'http://localhost:3000/auth/saml/callback'
    assertion_consumer_logout_service_url: 'http://localhost:3000/auth/saml/logout'
    sp_initiated_login_url: 'http://localhost:3000/admin/sign_in'
    block_encryption: 'aes256-cbc'
    cert: 'sp_micropurchase'
    logo: '18f.svg'
    agency: 'TTS Acquisition'
    friendly_name: 'Micro-purchase Dev'
    return_to_sp_url: 'http://localhost:3000'
    attribute_bundle:
      - email

  'urn:gov:gsa:SAML:2.0.profiles:sp:sso:micropurchase-staging':
    acs_url: 'https://micropurchase-staging.18f.gov/auth/saml/callback'
    assertion_consumer_logout_service_url: 'https://micropurchase-staging.18f.gov/auth/saml/logout'
    sp_initiated_login_url: 'https://micropurchase-staging.18f.gov/admin/sign_in'
    block_encryption: 'aes256-cbc'
    cert: 'sp_micropurchase'
    logo: '18f.svg'
    agency: 'TTS Acquisition'
    friendly_name: 'Micro-purchase Staging'
    return_to_sp_url: 'https://micropurchase-staging.18f.gov'
    attribute_bundle:
      - email

  'urn:gov:gsa:SAML:2.0.profiles:sp:sso:micropurchase-production':
    acs_url: 'https://micropurchase.18f.gov/auth/saml/callback'
    assertion_consumer_logout_service_url: 'https://micropurchase.18f.gov/auth/saml/logout'
    sp_initiated_login_url: 'https://micropurchase.18f.gov/admin/sign_in'
    block_encryption: 'aes256-cbc'
    cert: 'sp_micropurchase'
    agency: 'TTS Acquisition'
    logo: '18f.svg'
    allow_on_prod_chef_env: 'true'
    friendly_name: 'Micro-purchase'
    return_to_sp_url: 'https://micropurchase.18f.gov'
    attribute_bundle:
      - email

  # Dashboard
  'https://dashboard.demo.login.gov':
    friendly_name: 'Dashboard'
    agency: 'GSA'
    logo: '18f.svg'
    acs_url: 'https://dashboard.demo.login.gov/users/auth/saml/callback'
    assertion_consumer_logout_service_url: 'https://dashboard.demo.login.gov/users/auth/saml/logout'
    sp_initiated_login_url: 'https://dashboard.demo.login.gov/users/auth/saml'
    block_encryption: 'aes256-cbc'
    cert: 'identity_dashboard_cert'
    attribute_bundle:
      - email

  'https://dashboard.int.login.gov':
    friendly_name: 'Dashboard'
    agency: 'GSA'
    logo: '18f.svg'
    acs_url: 'https://dashboard.int.login.gov/users/auth/saml/callback'
    assertion_consumer_logout_service_url: 'https://dashboard.int.login.gov/users/auth/saml/logout'
    sp_initiated_login_url: 'https://dashboard.int.login.gov/users/auth/saml'
    block_encryption: 'aes256-cbc'
    cert: 'identity_dashboard_cert'
    attribute_bundle:
      - email

  'https://dashboard.qa.login.gov':
    friendly_name: 'Dashboard'
    agency: 'GSA'
    logo: '18f.svg'
    acs_url: 'https://dashboard.qa.login.gov/users/auth/saml/callback'
    assertion_consumer_logout_service_url: 'https://dashboard.qa.login.gov/users/auth/saml/logout'
    sp_initiated_login_url: 'https://dashboard.qa.login.gov/users/auth/saml'
    block_encryption: 'aes256-cbc'
    cert: 'identity_dashboard_cert'
    attribute_bundle:
      - email

  'https://dashboard.dev.login.gov':
    friendly_name: 'Dashboard'
    agency: 'GSA'
    logo: '18f.svg'
    acs_url: 'https://dashboard.dev.login.gov/users/auth/saml/callback'
    assertion_consumer_logout_service_url: 'https://dashboard.dev.login.gov/users/auth/saml/logout'
    sp_initiated_login_url: 'https://dashboard.dev.login.gov/users/auth/saml'
    block_encryption: 'aes256-cbc'
    cert: 'identity_dashboard_cert'
    attribute_bundle:
      - email

  'urn:gov:gsa:openidconnect:sp:sinatra':
    agency: 'GSA'
    cert: 'sp_sinatra_demo'
    friendly_name: 'Example Sinatra OIDC App'
    logo: '18f.svg'
    redirect_uris:
      - 'http://localhost:9292/'
      - 'https://sp-oidc-sinatra.dev.login.gov/'
      - 'https://sp-oidc-sinatra.dm.login.gov/'
      - 'https://sp-oidc-sinatra.int.login.gov/'
      - 'https://sp-oidc-sinatra.pt.login.gov/'
      - 'https://sp-oidc-sinatra.qa.login.gov/'
      - 'https://sp-oidc-sinatra.staging.login.gov/'

  # CBP Jobs
  'urn:gov:dhs.cbp.jobs:openidconnect:cert':
    redirect_uris:
      - 'https://careers-cert.cbp.dhs.gov/hrm/app'
    friendly_name: 'CBP Jobs'
    agency: 'DHS'
    logo: 'cbp.png'

  'urn:gov:dhs.cbp.jobs:openidconnect:cert:app':
    redirect_uris:
      - 'gov.dhs.cbp.jobs.applicant.cert://result'
    friendly_name: 'CBP Jobs'
    agency: 'DHS'
    logo: 'cbp.png'

  'urn:gov:dhs.cbp.jobs:openidconnect:prod':
    redirect_uris:
      - 'https://careers.cbp.dhs.gov/hrm/app'
    friendly_name: 'CBP Jobs'
    agency: 'DHS'
    logo: 'cbp.png'
    allow_on_prod_chef_env: 'true'

  'urn:gov:dhs.cbp.jobs:openidconnect:prod:app':
    redirect_uris:
      - 'gov.dhs.cbp.jobs.applicant://result'
    friendly_name: 'CBP Jobs'
    agency: 'DHS'
    logo: 'cbp.png'
    allow_on_prod_chef_env: 'true'

  # RRB
  'urn:gov:gsa:SAML:2.0.profiles:sp:sso:RRB:BOS-Pre-Prod':
    friendly_name: 'Railroad Retirement Board'
    agency: 'RRB'
    logo: 'rrb.svg'
    acs_url: 'https://onlinetest.rrb.gov/AA1/login/login/callback'
    assertion_consumer_logout_service_url: 'https://onlinetest.rrb.gov/AA1/BOS/BOS/logout'
    sp_initiated_login_url: 'https://onlinetest.rrb.gov/AA1/login/login/Auth'
    return_to_sp_url: 'https://onlinetest.rrb.gov/AA1/Login/login/RRBHome'
    block_encryption: 'aes256-cbc'
    cert: 'rrb_bos_pre_prod'
    attribute_bundle:
      - email
      - first_name
      - middle_name
      - last_name
      - address1
      - address2
      - city
      - state
      - zipcode
      - dob
      - ssn
      - phone

  # CBP GOES
  'urn:gov:dhs.cbp.jobs:openidconnect:jenkins-pspd-credential-service':
    friendly_name: 'CBP PSPD Trusted Traveler Programs'
    agency: 'DHS'
    logo: 'cbp.png'
    cert: 'cbp_goes_pre_prod'
    redirect_uris:
      - 'http://10.156.152.27/login'

  'urn:gov:dhs.cbp.jobs:openidconnect:aws-cbp-ttp':
    agency: 'DHS'
    allow_on_prod_chef_env: 'true'
    block_encryption: 'aes256-cbc'
    cert: 'cbp_goes_prod'
    friendly_name: 'CBP Trusted Traveler Programs'
    logo: 'cbp.png'
    redirect_uris:
      - 'https://ttp.cbp.dhs.gov'
